// Câu hỏi Ai là triệu phú: [câu hỏi, [đáp án…], chỉ số đáp án đúng]. Tránh câu phụ thuộc địa giới hành chính (đã sáp nhập tỉnh 2025).
export const MIL_Q=[
 [ // Dễ (câu 1–5)
  ['Bánh chưng ngày Tết thường được gói bằng lá gì?',['Lá chuối','Lá dong','Lá sen','Lá bàng'],1],
  ['Thủ đô của Việt Nam là?',['Hà Nội','TP. Hồ Chí Minh','Huế','Đà Nẵng'],0],
  ['1 kg bằng bao nhiêu gam?',['10','100','1.000','10.000'],2],
  ['Con vật nào KHÔNG có trong trò bầu cua tôm cá?',['Tôm','Gà','Nai','Heo'],3],
  ['Tết Trung thu vào ngày nào âm lịch?',['Rằm tháng Giêng','Rằm tháng Tám','Mùng 5 tháng 5','Mùng 1 tháng Giêng'],1],
  ['Một tuần có mấy ngày?',['5','6','7','8'],2],
  ['Tờ tiền mệnh giá lớn nhất Việt Nam đang lưu hành là?',['100.000đ','200.000đ','500.000đ','1.000.000đ'],2],
  ['Ở điều kiện thường, nước sôi ở bao nhiêu độ C?',['50','80','100','150'],2],
  ['Cầu vồng thường được kể có bao nhiêu màu?',['5','6','7','8'],2],
  ['Con vật nào được người Việt gọi là "chúa sơn lâm"?',['Voi','Hổ','Gấu','Khỉ'],1],
  ['Món nào có nước dùng, bánh phở và thịt bò hoặc gà?',['Phở','Bánh mì','Gỏi cuốn','Chè'],0],
  ['Tết Nguyên Đán còn được gọi là?',['Tết Tây','Tết ta','Tết Đoan Ngọ','Tết Thanh minh'],1],
  ['Mặt Trời mọc ở hướng nào?',['Đông','Tây','Nam','Bắc'],0],
  ['Con gì gáy "ò ó o" vào buổi sáng?',['Vịt','Gà trống','Chó','Mèo'],1],
  ['1 giờ có bao nhiêu phút?',['30','60','90','100'],1],
  ['Ngôi sao trên quốc kỳ Việt Nam màu gì?',['Trắng','Vàng','Đỏ','Xanh'],1],
  ['Trong 12 con giáp, năm Tý là năm con gì?',['Trâu','Chuột','Mèo','Hổ'],1],
  ['Muối ăn có vị gì?',['Ngọt','Mặn','Chua','Đắng'],1],
  ['Trái cây nào hay được gọi là "vua của các loại trái cây"?',['Sầu riêng','Xoài','Chuối','Ổi'],0],
  ['Hồ Gươm ở Hà Nội còn gọi là hồ gì?',['Hồ Tây','Hồ Hoàn Kiếm','Hồ Trúc Bạch','Hồ Xuân Hương'],1],
  ['Một năm dương lịch thường có bao nhiêu ngày?',['360','364','365','366'],2],
  ['Ngày Quốc tế Thiếu nhi là ngày nào?',['1/6','8/3','20/11','2/9'],0],
  ['Ngày Nhà giáo Việt Nam là ngày nào?',['20/10','20/11','8/3','1/5'],1],
  ['Quốc khánh nước Việt Nam là ngày nào?',['30/4','2/9','1/5','19/8'],1],
  ['Bia thường bán theo "lốc", 1 lốc thường có mấy lon?',['4','6','12','24'],1],
  ['Trứng bán theo vỉ 10 quả. 3 vỉ là bao nhiêu quả?',['13','20','30','33'],2],
  ['Khách mua 45.000đ, đưa tờ 50.000đ. Phải thối bao nhiêu?',['5.000đ','10.000đ','15.000đ','50.000đ'],0],
  ['Nước mắm truyền thống được làm chủ yếu từ gì?',['Cá và muối','Đậu nành','Tôm khô','Rong biển'],0],
  ['Con vật nào đẻ trứng?',['Mèo','Chó','Gà','Bò'],2],
  ['Hạt gì dùng để nấu cơm?',['Gạo','Đậu xanh','Bắp','Mè'],0],
 ],
 [ // Vừa (câu 6–10)
  ['Chợ nổi Cái Răng nằm ở thành phố nào?',['Hà Nội','Cần Thơ','Đà Nẵng','Huế'],1],
  ['Sông nào dài nhất chảy qua Việt Nam?',['Sông Hồng','Sông Mê Kông','Sông Đà','Sông Đồng Nai'],1],
  ['Đỉnh núi cao nhất Việt Nam là?',['Fansipan','Núi Bà Đen','Bạch Mã','Langbiang'],0],
  ['Tác giả của "Truyện Kiều" là ai?',['Nguyễn Du','Nguyễn Trãi','Hồ Xuân Hương','Nguyễn Đình Chiểu'],0],
  ['Trong xì dách, lá A đi với lá nào thì thành "xì dách"?',['2','5','K','9'],2],
  ['Tắm nắng buổi sáng giúp cơ thể tạo ra vitamin gì?',['A','B12','C','D'],3],
  ['Gửi 100 triệu, lãi 10%/năm. Sau 1 năm được bao nhiêu tiền lãi?',['1 triệu','10 triệu','11 triệu','100 triệu'],1],
  ['Mua 3 món giá 12.000đ, 15.000đ và 23.000đ. Tổng cộng là?',['40.000đ','45.000đ','50.000đ','55.000đ'],2],
  ['Nhập hàng 20.000đ, bán 25.000đ. Lãi bao nhiêu % so với giá vốn?',['5%','20%','25%','50%'],2],
  ['Bánh mì Việt Nam chịu ảnh hưởng từ ẩm thực nước nào?',['Pháp','Nhật','Mỹ','Ý'],0],
  ['Cà phê Việt Nam được trồng nhiều nhất ở vùng nào?',['Tây Nguyên','Đồng bằng sông Hồng','Tây Bắc','Duyên hải miền Trung'],0],
  ['Trong 12 con giáp của Việt Nam, con gì thay cho con thỏ?',['Mèo','Chó','Chuột','Cáo'],0],
  ['Ngày Phụ nữ Việt Nam là ngày nào?',['8/3','20/10','1/6','20/11'],1],
  ['Ngăn đá tủ lạnh thường để ở khoảng bao nhiêu độ?',['5°C','0°C','-18°C','-50°C'],2],
  ['Điện dân dụng ở Việt Nam dùng điện áp bao nhiêu?',['110V','220V','380V','12V'],1],
  ['Tết Hàn thực (ăn bánh trôi, bánh chay) vào ngày nào âm lịch?',['3/3','5/5','7/7','9/9'],0],
  ['Thành phố nào được gọi là "thành phố ngàn hoa"?',['Đà Lạt','Huế','Hội An','Nha Trang'],0],
  ['Ai đọc bản Tuyên ngôn Độc lập ngày 2/9/1945?',['Hồ Chí Minh','Võ Nguyên Giáp','Phạm Văn Đồng','Trường Chinh'],0],
  ['Chiến thắng Điện Biên Phủ diễn ra năm nào?',['1945','1954','1968','1975'],1],
  ['Đơn vị tiền tệ của Nhật Bản là?',['Won','Yên','Nhân dân tệ','Baht'],1],
  ['Hành tinh nào gần Mặt Trời nhất?',['Sao Kim','Sao Thủy','Trái Đất','Sao Hỏa'],1],
  ['Hình vuông cạnh 5 m có diện tích bao nhiêu?',['10 m²','20 m²','25 m²','50 m²'],2],
  ['Trong kinh doanh, "hàng tồn kho" là gì?',['Hàng đã bán','Hàng còn lại chưa bán','Hàng khách trả lại','Hàng tặng khách'],1],
  ['Cây xanh hấp thụ khí gì khi quang hợp?',['Oxy','CO₂','Nitơ','Heli'],1],
  ['Đàn bầu có mấy dây?',['1','2','3','4'],0],
  ['Không gian văn hóa cồng chiêng là di sản của vùng nào?',['Tây Nguyên','Tây Bắc','Nam Bộ','Đồng bằng sông Hồng'],0],
  ['Cầu Rồng phun lửa nổi tiếng ở thành phố nào?',['Đà Nẵng','Hải Phòng','Nha Trang','Quy Nhơn'],0],
  ['Ký hiệu hóa học "Fe" là nguyên tố gì?',['Sắt','Flo','Vàng','Bạc'],0],
  ['Kim tự tháp Giza nằm ở nước nào?',['Ai Cập','Mexico','Peru','Hy Lạp'],0],
  ['Đại dương lớn nhất thế giới là?',['Đại Tây Dương','Ấn Độ Dương','Thái Bình Dương','Bắc Băng Dương'],2],
  ['Công thức hóa học của nước là?',['H₂O','CO₂','O₂','NaCl'],0],
  ['"Dế Mèn phiêu lưu ký" do ai sáng tác?',['Tô Hoài','Nguyễn Nhật Ánh','Xuân Diệu','Tố Hữu'],0],
  ['Hàng giá 80.000đ, giảm 25% thì còn bao nhiêu?',['55.000đ','60.000đ','65.000đ','70.000đ'],1],
  ['1 lượng (1 cây) vàng bằng bao nhiêu chỉ?',['5','10','12','100'],1],
  ['Cột cờ Lũng Cú đánh dấu điểm cực nào của Việt Nam?',['Cực Bắc','Cực Nam','Cực Đông','Cực Tây'],0],
  ['Tổng ba góc trong một tam giác bằng bao nhiêu?',['90°','180°','270°','360°'],1],
  ['Căn bậc hai của 144 là?',['11','12','13','14'],1],
 ],
 [ // Khó (câu 11–15)
  ['Vua Quang Trung đại phá quân Thanh vào dịp nào?',['Tết Kỷ Dậu 1789','Tết Mậu Thân 1968','Năm 1802','Năm 1428'],0],
  ['Nhà Nguyễn đóng đô ở đâu?',['Phú Xuân (Huế)','Thăng Long','Hoa Lư','Gia Định'],0],
  ['Kinh đô của nhà Đinh là?',['Hoa Lư','Thăng Long','Phú Xuân','Cổ Loa'],0],
  ['Vua Lý Thái Tổ dời đô về Thăng Long năm nào?',['938','1010','1288','1428'],1],
  ['Trận Bạch Đằng năm 938 do ai chỉ huy?',['Ngô Quyền','Lê Hoàn','Trần Hưng Đạo','Lý Thường Kiệt'],0],
  ['Hệ Mặt Trời hiện có bao nhiêu hành tinh?',['7','8','9','10'],1],
  ['Tốc độ ánh sáng trong chân không xấp xỉ bao nhiêu?',['300.000 km/s','30.000 km/s','3.000 km/s','300 km/s'],0],
  ['Bột ngọt (mì chính) có thành phần chính là gì?',['Mononatri glutamat','Natri clorua','Sucrose','Axit axetic'],0],
  ['Giấm ăn chứa loại axit nào?',['Axit axetic','Axit sunfuric','Axit clohiđric','Axit nitric'],0],
  ['Số nguyên tố nhỏ nhất là?',['0','1','2','3'],2],
  ['Việt Nam bắt đầu phát hành tiền polymer từ năm nào?',['1995','2003','2010','2015'],1],
  ['Tiểu thuyết "Số đỏ" là của nhà văn nào?',['Vũ Trọng Phụng','Nam Cao','Ngô Tất Tố','Tô Hoài'],0],
  ['Nhân vật Chí Phèo là của nhà văn nào?',['Nam Cao','Vũ Trọng Phụng','Nguyễn Tuân','Kim Lân'],0],
  ['Chùa Một Cột được xây dựng lần đầu dưới triều đại nào?',['Nhà Lý','Nhà Trần','Nhà Lê','Nhà Nguyễn'],0],
  ['Văn Miếu (Hà Nội) được xây dựng năm nào?',['1070','1010','1225','1802'],0],
  ['Kênh đào Panama nối hai đại dương nào?',['Thái Bình Dương và Đại Tây Dương','Ấn Độ Dương và Thái Bình Dương','Đại Tây Dương và Ấn Độ Dương','Bắc Băng Dương và Đại Tây Dương'],0],
  ['Vĩ tuyến 17 gắn với con sông nào?',['Sông Bến Hải','Sông Thạch Hãn','Sông Hương','Sông Gianh'],0],
  ['Chất gì làm lá cây có màu xanh?',['Diệp lục','Carotene','Melanin','Hemoglobin'],0],
  ['Nhóm máu nào thường được gọi là nhóm "cho" phổ thông?',['O','A','B','AB'],0],
  ['Đơn vị đo cường độ dòng điện là gì?',['Vôn','Ampe','Oát','Ôm'],1],
  ['Điểm cực Đông phần đất liền Việt Nam là?',['Mũi Đôi','Mũi Cà Mau','Mũi Né','Lũng Cú'],0],
  ['Điểm cực Nam phần đất liền Việt Nam là?',['Mũi Cà Mau','Mũi Né','Mũi Đôi','Mũi Kê Gà'],0],
  ['Giá tăng từ 50.000đ lên 60.000đ là tăng bao nhiêu %?',['10%','15%','20%','25%'],2],
  ['Gửi 100 triệu, lãi kép 10%/năm. Sau 2 năm có tổng bao nhiêu?',['120 triệu','121 triệu','110 triệu','200 triệu'],1],
  ['Vàng "bốn số 9" (9999) có độ tinh khiết khoảng bao nhiêu?',['99,99%','99%','90%','75%'],0],
  ['Loài cá nào sống ở biển nhưng bơi ngược về sông để đẻ trứng?',['Cá hồi','Cá rô phi','Cá chép','Cá trê'],0],
  ['Trống đồng Đông Sơn thuộc thời kỳ nào?',['Thời đại đồ đồng – sắt','Thời đồ đá cũ','Thời nhà Nguyễn','Thời Pháp thuộc'],0],
  ['Theo truyền thuyết, bài thơ "Nam quốc sơn hà" gắn với ai?',['Lý Thường Kiệt','Trần Hưng Đạo','Lê Lợi','Quang Trung'],0],
  ['Phố cổ Hội An được UNESCO công nhận là di sản thế giới năm nào?',['1993','1999','2003','2010'],1],
  ['Nước nào đông dân nhất thế giới từ năm 2023?',['Trung Quốc','Ấn Độ','Mỹ','Indonesia'],1],
  ['Chữ cái đầu tiên trong bảng chữ cái Hy Lạp là?',['Alpha','Beta','Gamma','Omega'],0],
  ['Ai là người phát minh ra điện thoại (được cấp bằng sáng chế năm 1876)?',['Alexander Graham Bell','Thomas Edison','Isaac Newton','Albert Einstein'],0],
 ]];
